# Generated by Django 4.0.4 on 2022-07-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_remove_message_inbox_conversation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='participants',
        ),
    ]
