# Generated by Django 4.0.4 on 2022-08-25 04:26

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0005_alter_inbox_options_alter_conversation_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='uuid',
            field=models.CharField(default=common.utils.get_uuid_hex, max_length=32, verbose_name='uuid'),
        ),
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.CharField(default=common.utils.get_uuid_hex, max_length=32, verbose_name='uuid'),
        ),
    ]
