# Generated by Django 3.2 on 2022-03-15 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PE', 'Pre-Enrollment'), ('EN', 'Enrolled: Not Started'), ('ES', 'Enrolled: Started'), ('EG', 'Enrolled: Graduated'), ('EP', 'Enrolled: Academic Probation'), ('EE', 'Enrolled: Expelled')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users_app.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users_app.user',),
            managers=[
                ('objects', users_app.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users_app.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users_app.user',),
            managers=[
                ('objects', users_app.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='member_id',
            field=models.UUIDField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users_app.user')),
                ('paid_in_full', models.BooleanField(default=False)),
                ('enrollment_status', models.ForeignKey(default='PE', on_delete=django.db.models.deletion.SET_DEFAULT, to='users_app.enrollmentstatus')),
                ('funding_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users_app.fundingtype')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users_app.user',),
            managers=[
                ('objects', users_app.models.UserManager()),
            ],
        ),
    ]
