# Generated by Django 3.2 on 2022-03-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_alter_user_member_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Instructor'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student'},
        ),
        migrations.AlterModelOptions(
            name='teachingassistant',
            options={'verbose_name': 'Teaching Assistant'},
        ),
    ]
