# Generated by Django 3.2 on 2022-03-18 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20220316_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='tuition_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundingtype',
            name='title',
            field=models.CharField(choices=[('selfpay', 'Self Pay'), ('vettec', 'VETTEC'), ('vrrap', 'VRRAP'), ('gi_bill', 'G.I. Bill'), ('voc_rehab', 'Vocational Rehab'), ('ch_33', 'Chapter 33'), ('worksource', 'Worksource'), ('not_specified', 'Not Specified')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='users_app.enrollmentstatus'),
        ),
        migrations.AlterField(
            model_name='student',
            name='funding_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='students', to='users_app.fundingtype'),
        ),
    ]
