# Generated by Django 4.0.4 on 2022-05-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='cross_street_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cross street 1'),
        ),
        migrations.AddField(
            model_name='barter',
            name='cross_street_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cross street 2'),
        ),
        migrations.AddField(
            model_name='barter',
            name='latitude',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='barter',
            name='longitude',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='longitude'),
        ),
    ]
