# Generated by Django 4.0.4 on 2022-05-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0002_barter_cross_street_1_barter_cross_street_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedbarter',
            name='date_packaged',
        ),
        migrations.AddField(
            model_name='seedbarter',
            name='year_packaged',
            field=models.PositiveIntegerField(null=True, verbose_name='date_packaged'),
        ),
    ]
