# Generated by Django 4.0.4 on 2022-05-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0004_remove_plantbarter_age_plantbarter_date_planted'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='barter',
            name='quantity_units',
            field=models.CharField(choices=[('CT', 'count'), ('LB', 'pound'), ('CY', 'cubic yard')], default='CT', max_length=2, verbose_name='units'),
        ),
        migrations.AddField(
            model_name='toolbarter',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Height x Width x Length', max_length=64, null=True, verbose_name='dimensions'),
        ),
    ]
