# Generated by Django 4.0.4 on 2022-05-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0005_barter_quantity_barter_quantity_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='barter_type',
            field=models.CharField(choices=[('seed', 'Seed'), ('plant', 'Plant'), ('produce', 'Produce'), ('material', 'Material'), ('tool', 'Tool')], default='', max_length=10, verbose_name='barter type'),
        ),
        migrations.AlterField(
            model_name='barter',
            name='quantity_units',
            field=models.CharField(choices=[('PT', 'plant'), ('BC', 'bunch'), ('CT', 'count'), ('LB', 'pound'), ('CY', 'cubic yard')], default='CT', max_length=2, verbose_name='units'),
        ),
    ]
