# Generated by Django 4.0.4 on 2022-05-14 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0006_barter_barter_type_alter_barter_quantity_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='producebarter',
            name='barter_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='barters_app.barter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producebarter',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='common_name'),
        ),
        migrations.AddField(
            model_name='producebarter',
            name='genus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='genus'),
        ),
        migrations.AddField(
            model_name='producebarter',
            name='species',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='species'),
        ),
    ]
