# Generated by Django 4.0.4 on 2022-05-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0008_alter_barter_will_trade_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='date_expires',
            field=models.DateTimeField(null=True, verbose_name='expires on'),
        ),
    ]
