# Generated by Django 4.0.4 on 2022-05-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0009_alter_barter_date_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='date_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expires on'),
        ),
    ]
