# Generated by Django 4.0.4 on 2022-05-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0011_alter_barter_quantity_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='toolbarter',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Height x Width x Depth', max_length=64, null=True, verbose_name='dimensions'),
        ),
    ]
