# Generated by Django 4.0.4 on 2022-05-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0012_alter_barter_quantity_alter_toolbarter_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='quantity'),
        ),
    ]
