# Generated by Django 4.0.4 on 2022-06-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0013_alter_barter_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='barter',
            name='quantity_units',
            field=models.CharField(choices=[('NA', ''), ('PL', 'plant'), ('BC', 'bunch'), ('CT', 'count'), ('PK', 'package'), ('OZ', 'ounce'), ('LB', 'pound'), ('CY', 'cubic yard'), ('GL', 'gallon'), ('PT', 'pint')], default='NA', max_length=2, verbose_name='units'),
        ),
    ]
