# Generated by Django 4.0.4 on 2022-06-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0014_alter_barter_quantity_alter_barter_quantity_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producebarter',
            name='date_harvested',
        ),
    ]
