# Generated by Django 4.0.4 on 2022-06-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0015_remove_producebarter_date_harvested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantbarter',
            name='date_planted',
        ),
    ]
