# Generated by Django 4.0.4 on 2022-07-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_remove_message_inbox_conversation_and_more'),
        ('barters_app', '0016_remove_plantbarter_date_planted'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='conversations',
            field=models.ManyToManyField(related_name='barters', to='messages_app.conversation'),
        ),
    ]
