# Generated by Django 4.0.4 on 2022-07-26 04:22

import barters_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0017_barter_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='barter',
            name='uuid',
            field=models.UUIDField(default=barters_app.models.get_uuid_hex, verbose_name='uuid'),
        ),
    ]
