# Generated by Django 4.0.4 on 2022-07-26 04:29

import barters_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0018_barter_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='uuid',
            field=models.CharField(default=barters_app.models.get_uuid_hex, max_length=32, verbose_name='uuid'),
        ),
    ]
