# Generated by Django 4.0.4 on 2022-07-26 19:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0019_alter_barter_uuid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='barter',
            managers=[
                ('barter_list', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='materialbarter',
            managers=[
                ('barter_list', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='plantbarter',
            managers=[
                ('barter_list', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='producebarter',
            managers=[
                ('barter_list', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='seedbarter',
            managers=[
                ('barter_list', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='toolbarter',
            managers=[
                ('barter_list', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='seedbarter',
            name='year_packaged',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='date_packaged'),
        ),
    ]
