# Generated by Django 4.0.4 on 2022-07-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0005_alter_inbox_options_alter_conversation_recipient_and_more'),
        ('barters_app', '0020_alter_barter_managers_alter_materialbarter_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barter',
            name='conversations',
            field=models.ManyToManyField(blank=True, related_name='barters', to='messages_app.conversation'),
        ),
    ]
