# Generated by Django 4.0.4 on 2022-07-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0021_alter_barter_conversations'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='barter',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='materialbarter',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='plantbarter',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='producebarter',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='seedbarter',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='toolbarter',
            managers=[
            ],
        ),
    ]
