# Generated by Django 4.0.4 on 2022-07-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barters_app', '0022_alter_barter_managers_alter_materialbarter_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantbarter',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='plantbarter',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='plantbarter',
            name='species',
        ),
        migrations.RemoveField(
            model_name='producebarter',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='producebarter',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='producebarter',
            name='species',
        ),
        migrations.RemoveField(
            model_name='seedbarter',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='seedbarter',
            name='genus',
        ),
        migrations.RemoveField(
            model_name='seedbarter',
            name='species',
        ),
        migrations.RemoveField(
            model_name='seedbarter',
            name='year_packaged',
        ),
        migrations.RemoveField(
            model_name='toolbarter',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='barter',
            name='common_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='common_name'),
        ),
        migrations.AddField(
            model_name='barter',
            name='dimensions',
            field=models.CharField(blank=True, default=None, help_text='Height x Width x Depth', max_length=64, null=True, verbose_name='dimensions'),
        ),
        migrations.AddField(
            model_name='barter',
            name='genus',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='genus'),
        ),
        migrations.AddField(
            model_name='barter',
            name='species',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='species'),
        ),
        migrations.AddField(
            model_name='barter',
            name='year_packaged',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='date_packaged'),
        ),
    ]
